config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jobs, only: [:create]

  authenticate :account, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  scope "(:locale)", locale: /en|pt-BR|es|fr/ do
    get "health" => "rails/health#show", as: :rails_health_check
    get "errors/not_found"
    get "errors/internal_server_error"

    root to: "home#index"
    get "home/index"

    get "reduced_map", to: "home#reduced_map"
    get "map", to: "home#index"
    get "landing", to: "about#landing"
    get "about", to: "about#index"
    get "who_we_are", to: "about#who_we_are"
    get "how_to_register", to: "about#how_to_register"
    get "partners", to: "about#partners"
    get "friends", to: "about#partners"
    get "manual", to: "about#manual"
    get "license", to: "about#license"
    get "source_code_license", to: "about#source_code_license"
    get "thank_you_notes", to: "about#thank_you_notes"
    get "contact", to: "about#contact"
    get "projects_and_groups", to: "about#projectsandgroups"
    get "dashboard", to: "dashboard#index"
    get "privacy_policy", to: "about#privacy_policy"

    get "coordinates", to: "locations#coordinates"
    get "countries", to: "locations#countries"
    get "/gallery", to: "medias#gallery"

    put "/practices/:id/like", to: "practices#like", as: "like_practice"
    put "/locations/:id/like", to: "locations#like", as: "like_location"
    post "/accounts/:id/message", to: "accounts#message", as: "message_account"
    post "/home/message", to: "home#message", as: "message_contact"
    post "/locations/:id/sensors", to: "locations#sensors", as: "sensors_location"
    get "/locations/:id/sensors", to: "locations#show_sensors", as: "show_sensors_location"

    resources :practices
    resources :acknowledges
    resources :evaluates
    resources :characterises
    resources :what_you_dos
    resources :comments

    resources :practices do
      resources :acknowledges
      resources :evaluates
      resources :characterises
      resources :what_you_dos
      resources :medias
      resources :documents
      resources :comments
      get "/gallery" => "medias#gallery"
    end

    resources :locations do
      get "/gallery" => "medias#gallery"
      resources :practices
      resources :medias
      resources :documents
    end

    devise_for :accounts, controllers: {
      registrations: "accounts/registrations",
      sessions: "accounts/sessions",
      confirmations: "accounts/confirmations"
    }

    resources :accounts do
      resources :locations
      resources :practices
      resources :medias
      get "/gallery" => "medias#gallery"
    end

    post "login", to: "authentication#login"
    post "signup", to: "authentication#signup"
    post "validate_jwt_token", to: "authentication#validate_jwt_token"

    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
    match "/422", to: "errors#unprocessable_entity", via: :all

    scope(accounts: {}) do
      resources :accounts, path: "usuarios"
      resources :accounts, path: "contributors"
    end

    scope(locations: {}) do
      resources :locations, path: "locais"
    end

    scope(practices: {}) do
      resources :practices, path: "agroecological-experiences"
      resources :practices, path: "experiencia_agroecologicas"
      resources :practices, path: "agroforestry"
      resources :practices, path: "experiences"
      resources :practices, path: "safs"
      resources :practices, path: "news"
    end
  end
end

app/models/media.rb
# frozen_string_literal: true

class Media < ApplicationRecord
  paginates_per 8

  belongs_to :location, required: false
  belongs_to :practice, required: false
  belongs_to :account, required: false

  has_one_attached :photo do |attachable|
    attachable.variant :original, { resize_to_limit: [1920, nil], convert: :webp, saver: { subsample_mode: "on", strip: true, interlace: true, quality: 85 } }
    attachable.variant :medium, { resize_to_limit: [600, nil], convert: :webp, saver: { subsample_mode: "on", strip: true, interlace: true, quality: 85 } }
    attachable.variant :thumb, { resize_to_limit: [300, nil], convert: :webp, saver: { subsample_mode: "on", strip: true, interlace: true, quality: 85 } }
  end

  validates :photo, presence: true
  validate :acceptable_photo
  validates_length_of :description, maximum: 255, allow_blank: true

  before_save do
    self.description = description.strip if attribute_present?("description")
  end
  def acceptable_photo
    return unless photo.attached?

    unless photo.blob.byte_size <= 16.megabyte
      errors.add(:photo, "Size Limit is 16 Mb")
    end

    acceptable_types = ["image/jpeg", "image/png", "image/gif", "image/webp"]
    unless acceptable_types.include?(photo.content_type)
      errors.add(:photo, "must be a JPEG, PNG, GIF or WebP")
    end
  end
end

app/controllers/medias_controller.rb
# frozen_string_literal: true

class MediasController < ApplicationController
  skip_before_action :authenticate, except: %i[index, show], if: -> { request.format.json? }

  before_action :authenticate_account!, only: %i[new edit update destroy], if: -> { !request.format.json? }

  before_action :set_media, only: %i[show edit update destroy]
  before_action -> { check_owner Media.find(params[:id]).account_id }, only: %i[edit update destroy]
  before_action :load_dados
  before_action :selected_id
  before_action :load_medias

  # GET /medias
  # GET /medias.json
  def index
  end

  # GET /gallery
  # GET /gallery.json
  def gallery
  end

  # GET /medias/1
  # GET /medias/1.json
  def show; end

  # GET /medias/new
  def new
    @media = Media.new
  end

  # GET /medias/1/edit
  def edit; end

  # POST /medias
  # POST /medias.json
  def create
    @media = Media.new(media_params)

    if request.format.json?
      if params[:base64Image]
        base64Image = params[:base64Image]
        decoded_data = Base64.decode64(base64Image)
        @media.photo = {
                            io: StringIO.new(decoded_data),
                            content_type: "image/jpeg",
                            filename: "image.jpg"
                          }
      end
      @media.account_id = authenticate.id
    else
      @media.account_id = current_account.id unless current_account.admin?
    end

    if params[:practice_id]
      @media.practice_id = @practice.id
      @media.location_id = @practice.location.id
    elsif params[:location_id]
      @media.location_id = @location.id
    end

    respond_to do |format|
      if @media.save
        if params[:practice_id]
          format.html { redirect_to new_practice_media_path(@practice), notice: "Media has been sent" }
        elsif params[:location_id]
          format.html do
            redirect_to new_location_media_path(@location),  notice: "Media has been sent"
          end
        end
        format.json { render json: { message: "created" }, status: :created }
      else
        format.html { render :new }
        format.json { render json: { error: @media.errors }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medias/1
  # PATCH/PUT /medias/1.json
  def update
    respond_to do |format|
      if @media.update(media_params)
        if params[:practice_id]
          format.html { redirect_to practice_gallery_path(@practice), notice: "Media has been updated." }
        elsif params[:location_id]
          format.html do
            redirect_to location_gallery_path(@location),  notice: "Media has been updated."
          end
        end
        format.json { render :show, status: :ok, location: @media }
      else
        format.html { render :edit }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medias/1
  # DELETE /medias/1.json
  def destroy
    @media.destroy

    respond_to do |format|
      if params[:practice_id]
        format.html { redirect_to practice_gallery_path(@practice), notice: "Media has been removed." }
      elsif params[:location_id]
        format.html do
          redirect_to location_gallery_path(@location), notice: "Media has been removed."
        end
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media
      @media = Media.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_params
      if request.format.json?
        params.require(:media).permit(:description, :practice_id, :location_id, :photo, :account_id, :base64Image)
      else
        params.require(:media).permit(:description, :practice_id, :location_id, :photo, :account_id)
      end
    end

    def load_dados
      if params[:practice_id]
        @practice = Practice.friendly.find(params[:practice_id])
      elsif params[:location_id]
        @location = Location.friendly.find(params[:location_id])
      elsif params[:account_id]
        @account = Account.friendly.find(params[:account_id])
      end
    end

    def selected_id
      if !request.format.json?
        if current_account && current_account.admin?
          @selected_id = current_account.id
          if @practice
            @selected_id = @practice.account.id
          elsif @location
            @selected_id = @location.account.id
          end
        end
      end
    end

    def load_medias
      @full_gallery = false
      if params[:practice_id]
        @medias = Media.where(practice_id: @practice.id).order("updated_at DESC").page(params[:page])
      elsif params[:location_id]
        @medias = Media.where(location_id: @location.id).order("updated_at DESC").page(params[:page])
      elsif params[:account_id]
        @medias = Media.where(account_id: @account.id).order("updated_at DESC").page(params[:page])
      else
        @full_gallery = true
        @total_media = Media.all.count
        @medias = Media.all.order("updated_at DESC").page(params[:page])
      end
    end
end

app/views/medias/_form.html.erb
<%= form_for_media params do |f| %>
  <% if media.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(media.errors.count, "error") %> encontrado(s):</h2>

      <ul>
        <% media.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="forms">
    <% if current_account.admin? %>
      <div class="form-group row">
        <%= f.label t(:responsible_for_information), class: "col-sm-2 col-form-label col-form-label-lg" %>
        <div class="col-sm-10">
          <%= f.collection_select(:account_id, Account.all, :id, :name, {:selected => @selected_id }, { class: "form-control selectpicker", "data-live-search": true }) %>
        </div>
      </div>
      <br>
    <% end %>
    <div class="form-group required row">
      <%= f.label t(:photo), class: "col-sm-2 col-form-label col-form-label-lg control-label" %>
      <div class="col-sm-8">
        <%= f.file_field :photo, class: "form-control", :required => params["action"] == 'edit' ||  params["action"] == 'update' ? false : true %>
        <div class="tip">
          File Format: PNG, JPG or GIF. Size Limit: 16MB.
          <%= "<span class='tip_alert' style='float: right;'>*#{t(:this_field_is_required)}.</span>".html_safe unless (params["action"] == 'edit' ||  params["action"] == 'update') %>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group row bg-light">
      <%= f.label t(:description), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.text_field :description,  class: "form-control" %>
        <div class="tip">(Minimum Size: 4 / Maximum Size: 128)</div>
      </div>
    </div>
  </div>
  <hr>
  <div class="actions">
    <%= f.submit t(:save), class: "btn btn-warning btn-lg" %>
  </div>
<% end %>

<% if not @medias.blank? and params["action"] == 'new'%>
  <br><br>
  <div class="row">
    <% @medias.each do |media| %>
      <div class="col-sm-6" style="cursor: pointer;" >
        <div class="card" style="max-height: <%= account_signed_in? ? '340px' : '280px'%>;">
          <br>
          <div class="card-img-top thumbnail" >
            <a href="<%= url_for(media.photo.variant(:original)) %>>" data-toggle="lightbox" data-gallery="media-gallery" data-max-width="900">
              <img src="<%= url_for(media.photo.variant(:medium)) %>" alt="Photo <%= media.description %>" title="Photo <%= media.description %>" class="img-fluid">
            </a>
          </div>
          <div class="card-body"  style="min-height: 180px;">
            <p class="card-text text-box"><%= media.description.truncate(100) unless media.description.blank? %></p>
            <% if account_signed_in? %>
              <% if current_account.admin? or media.account.id == current_account.id %>
                <% if params[:location_id] %>
                  <td><%= link_to t(:destroy), location_media_path(media.location, media), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
                <% elsif params[:practice_id] %>
                  <td><%= link_to t(:destroy), practice_media_path(media.practice, media), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
                <% end %>
              <% else %>
                <br><br>
              <% end %>
            <% end %>
          </div>
        </div>
        <br>
      </div>
    <% end %>
  </div>

  <div>
    <%= paginate @medias %>
  </div>
  <br><br>
  <script>
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
          event.preventDefault();
          $(this).ekkoLightbox();
      });
  </script>
<% end %>

app/views/medias/edit.html.erb
<% if params[:practice_id] %>
  <% title "Edit" %>
<% elsif params[:location_id] %>
  <% title "Edit" %>
<% end %>

<% if account_signed_in? %>
  <% if params[:practice_id] %>
    <div class="link-action">
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@practice), :class => "btn btn-warning" %>
      <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@practice), :class => "btn btn-secondary" %>
    </div>
  <% end %>
<% end %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to truncate(@location.name, length: 25), location_path(@location), :class => "nav-link" %>
    </li>

    <% if account_signed_in? %>
      <li class="nav-item">
        <%= link_to t(:send_photo), new_location_media_path, :class => "nav-link active" %>
      </li>
    <% end %>
  <% end %>

  <% if params[:practice_id] %>
    <li class="nav-item">
      <%= link_to truncate(@practice.location.name, length: 12), location_path(@practice.location), title: @practice.location.name,  :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to @practice.name.truncate(18) , practice_path(@practice), :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(:what_you_do), practice_what_you_do_path(@practice, @practice.what_you_do), :class => "nav-link" if @practice.what_you_do %>
    </li>
    <li class="nav-item">
      <%= link_to t(:characterise), practice_characterise_path(@practice, @practice.characterise), :class => "nav-link" if @practice.characterise %>
    </li>
    <li class="nav-item">
      <%= link_to "#{t(:gallery)} (#{@practice.medias.count})", practice_gallery_path(@practice), :class => "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "#{t(:documents)} (#{@practice.documents.count})", practice_documents_path(@practice), :class => "nav-link" %>
    </li>
  <% end %>
</ul>

<br>

<%= render 'form', media: @media %>

app/views/medias/gallery.html.erb
<% title t(:gallery) + " #{@location.name}" if params[:location_id] %>
<% title t(:gallery) + " #{@practice.name}" if params[:practice_id] %>
<% title t(:gallery) + " #{@account.name}" if params[:account_id] %>
<% title t(:gallery) if @full_gallery %>

<div class="link-action">
<% if account_signed_in? %>
  <% if params[:location_id] %>
    <% if current_account.admin? or current_account.id == @location.account.id %>
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_location_media_path, :class => "btn btn-warning" if current_account.admin? or @location.account_id == current_account.id %>
    <% end %>
  <% end %>
<% end %>

<% if account_signed_in? %>
  <% if params[:practice_id] %>
    <% if current_account.admin? or current_account.id == @practice.account.id %>
        <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@practice), :class => "btn btn-warning" %>
        <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@practice), :class => "btn btn-secondary" %>
    <% end %>
  <% end %>
<% end %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to truncate(@location.name, length: 25), location_path(@location), :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(:practices) + " (#{@location.practices.count})", location_practices_path(@location), :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(:gallery)+ " (#{@location.medias.count})", location_path(@location), :class => "nav-link active" %>
    </li>
  <% end %>

  <% if params[:practice_id] %>
    <li class="nav-item">
      <%= link_to truncate(@practice.location.name, length: 12), location_path(@practice.location), title: @practice.location.name,  :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to @practice.name.truncate(18) , practice_path(@practice), :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(:what_you_do), practice_what_you_do_path(@practice, @practice.what_you_do), :class => "nav-link" if @practice.what_you_do %>
    </li>
    <li class="nav-item">
      <%= link_to t(:characterise), practice_characterise_path(@practice, @practice.characterise), :class => "nav-link" if @practice.characterise %>
    </li>
    <li class="nav-item">
      <%= link_to "#{t(:gallery)} (#{@practice.medias.count})", practice_gallery_path(@practice), :class => "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "#{t(:documents)} (#{@practice.documents.count})", practice_documents_path(@practice), :class => "nav-link" %>
    </li>
  <% end %>

  <% if params[:account_id] %>
      <%= link_to t(:gallery) + " #{ @account.blank? ? '' : ' (' + @account.name.truncate(16) + ')' }", account_path(@account), :class => "nav-link active" %>
  <% end %>

  <% if @full_gallery %>
  <%= link_to "#{t(:gallery)} (#{@medias.count} of #{@total_media})", "#", :class => "nav-link active" %>
  <% end %>
</ul>

<% if @medias.empty? %>
  <br><br>

  <h2><%= t(:no_photo_submitted) %>
    <% if account_signed_in? %>
      <% if params[:practice_id] %>
        <%= link_to t(:send_picture), new_practice_media_path(@practice) if current_account.admin? or @practice.account_id == current_account.id %>
      <% end %>
    <% end %>
  </h3>

<% else %>
  <br>
  <div class="row">
    <% @medias.each do |media| %>
      <div class="col-sm-3" style="cursor: pointer;" >
        <div class="card" style="max-height: <%= account_signed_in? ? '375px' : '325px'%>;">
          <br>
          <div class="card-img-top thumbnail" >
            <a href="<%= url_for(media.photo.variant(:original)) %>>" data-toggle="lightbox" data-gallery="media-gallery" data-max-width="900">
              <img src="<%= url_for(media.photo.variant(:thumb)) %>" alt="Photo <%= media.description %>" title="Photo <%= media.description %>" class="img-fluid">
            </a>
          </div>
          <div class="card-body"  style="min-height: 180px;">
            <h4 class="card-title" style="font-size: 18px !important; word-break: break-all;">
             <a href="<%= url_for(media.photo.variant(:original)) %>>" data-toggle="lightbox" data-gallery="media-gallery" data-max-width="900">
             <%= media.description.squish!.strip.truncate(55) %>
             </a>
            </h4>
            <p class="card-text" style="text-align: center; font-size: 12px;">
              Photo sent by <%= link_to media.account.name.truncate(18), account_path(media.account) if media.location %>
              at 
              <%= link_to media.location.name.truncate(21), location_path(media.location) if media.location %>
            </p>
            <% if account_signed_in? %>
              <% if current_account.admin? or media.account.id == current_account.id %>
                <% if params[:location_id] %>
                  <td><%= link_to t(:edit), edit_location_media_path(media.location, media), :class => 'btn btn-sm btn-success' %></td>
                  <td><%= link_to t(:destroy), location_media_path(media.location, media), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
                <% elsif params[:practice_id] %>
                  <td><%= link_to t(:edit), edit_practice_media_path(media.practice, media), :class => 'btn btn-sm btn-success' %></td>
                  <td><%= link_to t(:destroy), location_media_path(media.location, media), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
                <% end %>
              <% else %>
                <br><br>
              <% end %>
            <% end %>
          </div>
        </div>
        <br>
      </div>
    <% end %>
  </div>

  <div>
    <%= paginate @medias %>
  </div>
  <br>
  <script>
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
          event.preventDefault();
          $(this).ekkoLightbox();
      });
  </script>
<% end %>

app/views/medias/index.html.erb
<% if params[:practice_id] %>
  <% title t(:photo) + " #{@practice.name}" %>
<% end %>

<div class="link-action">
<% if account_signed_in? %>
  <% if params[:practice_id] %>
    <%= link_to t(:send_picture), new_practice_media_path, :class => "btn btn-warning", :style => "float:right;" if current_account.admin? or @practice.account_id == current_account.id %>
  <% end %>
<% end %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <% if params[:practice_id] %>
      <%= link_to truncate(@practice.name, length: 25), practice_path(@practice), :class => "nav-link" %>
  <% end %>
  </li>

  <li class="nav-item">
    <% if params[:practice_id] %>
      <%= link_to t(:gallery) + " (#{@practice.medias.count})", practice_gallery_path, :class => "nav-link", :style => "color: red !important" %>
    <% end %>
  </li>

  <li class="nav-item">
    <% if params[:practice_id] %>
      <%= link_to t(:photos) + " (#{@practice.medias.count})", practice_medias_path, :class => "nav-link active" %>
    <% end %>
  </li>
</ul>

<% if @medias.empty? %>
  <br>

  <h3><%= t(:no_photo_submitted) %>
    <% if account_signed_in? %>
      <% if params[:practice_id] %>
        <%= link_to t(:send_picture), new_practice_media_path(@practice) if current_account.admin? or @practice.account_id == current_account.id %>
      <% end %>
    <% end %>
  </h3>

<% else %>

  <br>
  <div>
    <table class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
      <tr>
        <th></th>
        <th><%= t(:description) %></th>
        <% if account_signed_in? %>
          <th class="list-control"></th>
          <th class="list-control"></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% @medias.each do |media| %>
        <tr>
          <% if params[:practice_id] %>
            <td scope="row"><div class="thumbnail-mini"><%= link_to photo_medium(media, media.description), practice_media_path(@practice, media) %></div></td>
            <td><%= link_to media.description, practice_media_path(@practice, media) %></td>
          <% end %>

          <% if account_signed_in? %>
            <% if current_account.admin? or media.account_id == current_account.id %>
              <% if params[:practice_id] %>
                <td><%= link_to t(:edit), edit_practice_media_path(@practice, media), :class => 'btn btn-sm btn-success' %></td>
                <td><%= link_to t(:destroy), practice_media_path(@practice, media), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
              <% end %>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/medias/new.html.erb
<% if params[:practice_id] %>
  <% title "Add Photo To #{@practice.name}" %>
<% elsif params[:location_id] %>
  <% title "Add Photo to #{@location.name}" %>
<% end %>

<% if account_signed_in? %>
  <% if params[:practice_id] %>
    <div class="link-action">
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@practice), :class => "btn btn-warning" %>
      <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@practice), :class => "btn btn-secondary" %>
    </div>
  <% elsif params[:location_id] %>
    <div class="link-action">
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_location_media_path(@location), :class => "btn btn-warning" %>
    </div>
  <% end %>
<% end %>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to truncate(@location.name, length: 25), location_path(@location), :class => "nav-link" %>
    </li>

    <% if account_signed_in? %>
      <li class="nav-item">
        <%= link_to t(:send_photo), new_location_media_path, :class => "nav-link active" %>
      </li>
    <% end %>
  <% end %>

  <% if params[:practice_id] %>
    <li class="nav-item">
      <%= link_to truncate(@practice.location.name, length: 12), location_path(@practice.location), title: @practice.location.name,  :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to @practice.name.truncate(18) , practice_path(@practice), :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t(:what_you_do), practice_what_you_do_path(@practice, @practice.what_you_do), :class => "nav-link" if @practice.what_you_do %>
    </li>
    <li class="nav-item">
      <%= link_to t(:characterise), practice_characterise_path(@practice, @practice.characterise), :class => "nav-link" if @practice.characterise %>
    </li>
    <li class="nav-item">
      <%= link_to "#{t(:gallery)} (#{@practice.medias.count})", practice_gallery_path(@practice), :class => "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "#{t(:documents)} (#{@practice.documents.count})", practice_documents_path(@practice), :class => "nav-link" %>
    </li>
  <% end %>
</ul>

<br>

<%= render 'form', media: @media %>