config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jobs, only: [:create]

  authenticate :account, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  scope "(:locale)", locale: /en|pt-BR|es|fr/ do
    get "health" => "rails/health#show", as: :rails_health_check
    get "errors/not_found"
    get "errors/internal_server_error"

    root to: "home#index"
    get "home/index"

    get "reduced_map", to: "home#reduced_map"
    get "map", to: "home#index"
    get "landing", to: "about#landing"
    get "about", to: "about#index"
    get "who_we_are", to: "about#who_we_are"
    get "how_to_register", to: "about#how_to_register"
    get "partners", to: "about#partners"
    get "friends", to: "about#partners"
    get "manual", to: "about#manual"
    get "license", to: "about#license"
    get "source_code_license", to: "about#source_code_license"
    get "thank_you_notes", to: "about#thank_you_notes"
    get "contact", to: "about#contact"
    get "projects_and_groups", to: "about#projectsandgroups"
    get "dashboard", to: "dashboard#index"
    get "privacy_policy", to: "about#privacy_policy"

    get "coordinates", to: "locations#coordinates"
    get "countries", to: "locations#countries"
    get "/gallery", to: "medias#gallery"

    put "/practices/:id/like", to: "practices#like", as: "like_practice"
    put "/locations/:id/like", to: "locations#like", as: "like_location"
    post "/accounts/:id/message", to: "accounts#message", as: "message_account"
    post "/home/message", to: "home#message", as: "message_contact"
    post "/locations/:id/sensors", to: "locations#sensors", as: "sensors_location"
    get "/locations/:id/sensors", to: "locations#show_sensors", as: "show_sensors_location"

    resources :practices
    resources :acknowledges
    resources :evaluates
    resources :characterises
    resources :what_you_dos
    resources :comments

    resources :practices do
      resources :acknowledges
      resources :evaluates
      resources :characterises
      resources :what_you_dos
      resources :medias
      resources :documents
      resources :comments
      get "/gallery" => "medias#gallery"
    end

    resources :locations do
      get "/gallery" => "medias#gallery"
      resources :practices
      resources :medias
      resources :documents
    end

    devise_for :accounts, controllers: {
      registrations: "accounts/registrations",
      sessions: "accounts/sessions",
      confirmations: "accounts/confirmations"
    }

    resources :accounts do
      resources :locations
      resources :practices
      resources :medias
      get "/gallery" => "medias#gallery"
    end

    post "login", to: "authentication#login"
    post "signup", to: "authentication#signup"
    post "validate_jwt_token", to: "authentication#validate_jwt_token"

    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
    match "/422", to: "errors#unprocessable_entity", via: :all

    scope(accounts: {}) do
      resources :accounts, path: "usuarios"
      resources :accounts, path: "contributors"
    end

    scope(locations: {}) do
      resources :locations, path: "locais"
    end

    scope(practices: {}) do
      resources :practices, path: "agroecological-experiences"
      resources :practices, path: "experiencia_agroecologicas"
      resources :practices, path: "agroforestry"
      resources :practices, path: "experiences"
      resources :practices, path: "safs"
      resources :practices, path: "news"
    end
  end
end

app/models/what_you_do.rb
# frozen_string_literal: true

class WhatYouDo < ApplicationRecord
  belongs_to :practice
  validates :practice, presence: true
end

app/controllers/what_you_dos_controller.rb
# frozen_string_literal: true

class WhatYouDosController < ApplicationController
  skip_before_action :authenticate, except: %i[index, show], if: -> { request.format.json? }
  before_action :authenticate_account!, only: %i[new edit update destroy], if: -> { !request.format.json? }

  before_action -> { check_owner WhatYouDo.find(params[:id]).practice.account_id }, only: %i[edit update destroy]
  before_action :set_what_you_do, only: %i[ show edit update destroy ]
  before_action :authenticate_account!, only: %i[new edit update destroy]
  before_action :load_options_what_you_do
  before_action :load_yes_no_i_am_not_sure_options

  # GET /what_you_dos or /what_you_dos.json
  def index
    @what_you_dos = WhatYouDo.all
  end

  # GET /what_you_dos/1 or /what_you_dos/1.json
  def show
  end

  # GET /what_you_dos/new
  def new
    begin
      @practice = Practice.friendly.find(params[:practice_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to locations_path, notice: "This Practice doesn't exist."
    end

    # ToDo: Recover Data Between Navigation
    # @what_you_do_prev = WhatYouDo.where(practice_id: @practice.id).first
    @what_you_do = WhatYouDo.new
    # @what_you_do.summary_description_of_agroecological_practice = @what_you_do_prev.summary_description_of_agroecological_practice
  end

  # GET /what_you_dos/1/edit
  def edit
  end

  # POST /what_you_dos or /what_you_dos.json
  def create
    @what_you_do = WhatYouDo.where(practice_id: params[:what_you_do][:practice_id]).first

    respond_to do |format|
      if @what_you_do
        @what_you_do.update(what_you_do_params)
        format.html { redirect_to new_practice_characterise_path(@what_you_do.practice), notice: "What you do was successfully Updated." }
        format.json { render json: { message: "created" }, status: :created }
      else
        @what_you_do = WhatYouDo.new(what_you_do_params)
        if @what_you_do.save
          format.html { redirect_to new_practice_characterise_path(@what_you_do.practice), notice: "What you do was successfully created." }
          format.json { render :show, status: :created, location: @what_you_do }
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @what_you_do.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /what_you_dos/1 or /what_you_dos/1.json
  def update
    respond_to do |format|
      if @what_you_do.update(what_you_do_params)
        format.html { redirect_to what_you_do_url(@what_you_do), notice: "What you do was successfully updated." }
        format.json { render :show, status: :ok, location: @what_you_do }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @what_you_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /what_you_dos/1 or /what_you_dos/1.json
  def destroy
    @practice = @what_you_do.practice
    @what_you_do.destroy

    respond_to do |format|
      format.html { redirect_to practice_path(@practice), notice: "What you do was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_what_you_do
      @what_you_do = WhatYouDo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def what_you_do_params
      params.require(:what_you_do).permit(:practice_id, :where_it_is_realized, :land_size, :substitution_of_less_ecological_alternative, :summary_description_of_agroecological_practice,
                                          :type_of_agroecological_practice, :practical_implementation_of_the_practice,
                                          :why_you_use_and_what_you_expect_from_this_practice, :substitution_of_less_ecological_alternative_details, :unit_of_measure)
    end
end

app/views/what_you_dos/_form.html.erb
<%= form_for(what_you_do, html: { multipart: true }) do |f| %>
  <% button_name = params["action"] == 'edit' ? t(:save) :  t(:next ) %>
  <%= f.submit button_name, class: "btn btn-warning btn-lg", style: "float: right; margin-bottom: 16px;" %>

  <br><br>

  <% if what_you_do.errors.any? %>
    <div id="error_explanation">
      <b><%= what_you_do.errors.count.to_s + " Error(s)" %></b>
      <br><br>
      <% what_you_do.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %><br>
    </div>

  <% end %>

  <div class="form-group row">
    <div class="col-sm-10">
      <% if params[:practice_id] %>
        <%= f.hidden_field :practice_id, id: "practice_id", :value => Practice.friendly.find(params[:practice_id]).id %>
      <% else %>
        <%= f.hidden_field :practice_id, id: "practice_id", :value => @what_you_do.practice.id %>
      <% end %>
    </div>
  </div>

  <div class="forms">
    <div class="form-group row bg-light required">
      <%= f.label t(:summary_description_of_agroecological_practice), class: "col-sm-2 col-form-label col-form-label-lg control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select(:where_it_is_realized, @where_it_is_realized_options, :last, :first, { :include_blank => false }, { class: "form-control selectpicker", "data-live-search": true }) %>
        <%= f.text_area :summary_description_of_agroecological_practice, class: "form-control", :rows => "6", :required => true %>
        <div class="tip">
          <%= t(:in_short_what_is_the_practice_that_you_want_to_map) %>
          <span class="tip_alert" style="float: right;">*<%= t(:this_field_is_required) %>.</span>
        </div>
      </div>
    </div>
    <!--
    <br>
    <div class="form-group row">
      <%= f.label t(:type_of_agroecological_practice), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.text_area :type_of_agroecological_practice, class: "form-control", :rows => "6" %>
        <div class="tip">
          <%= t(:type_of_agroecological_practice_tip) %>
        </div>
      </div>
    </div>

    <br>
    <div class="form-group row bg-light">
      <%= f.label t(:practical_implementation_of_the_practice), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.text_area :practical_implementation_of_the_practice, class: "form-control", :rows => "6" %>
        <div class="tip">
          <%= t(:how_do_you_do_prepare_and_or_implement_the_practice) %>
        </div>
      </div>
    </div>

    <br>
    <div class="form-group row">
      <%= f.label t(:land_size), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:unit_of_measure, @unit_of_measure_options, :last, :first, { :include_blank => t(:unit_of_measurement) }, { class: "form-control selectpicker", "data-live-search": true }) %>
        <%= f.number_field :land_size, class: "form-control", step: 0.1 %>
        <div class="tip">
          <%= t(:on_how_much_land_do_you_implement_the_practice) %>
        </div>
      </div>
    </div>

    <br>
    <div class="form-group row bg-light">
      <%= f.label t(:substitution_of_less_ecological_alternative), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:substitution_of_less_ecological_alternative, @yes_no_i_am_not_sure_not_applicable_options, :last, :first, { :include_blank => t(:select_an_option) }, { class: "form-control selectpicker", "data-live-search": true }) %>
        <%= f.text_area :substitution_of_less_ecological_alternative_details, class: "form-control", :rows => "3", :placeholder => t(:please_provide_additional_details) %>
        <div class="tip">
          <%= t(:does_the_practice_substitute_and_or_reduce_a_less_ecological_alternative_ie_use_of_synthetic_inputs) %>
        </div>
      </div>
    </div>

    <br>
    <div class="form-group row ">
      <%= f.label t(:why_you_use_and_what_you_expect_from_this_practice), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.text_area :why_you_use_and_what_you_expect_from_this_practice, class: "form-control", :rows => "6" %>
        <div class="tip">
          <%= t(:which_effect_do_you_expect_the_practice_to_have) %>
        </div>
      </div>
    </div>
    -->
    <%= f.submit button_name, class: "btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/what_you_dos/edit.html.erb
<% title t(:what_you_do) %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to @what_you_do.practice.name.truncate(25), practice_path(@what_you_do.practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)}", "#", :class => "nav-link active" %>
  </li>
</ul>
<br>

<%= render 'form', what_you_do: @what_you_do %>

app/views/what_you_dos/new.html.erb
<% title t(:what_you_do) %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to t(:practices), practices_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), "#", :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), "#", :class => "nav-link" %>
  </li>
</ul>

<br>

<div class="tip"><%= t(:if_you_dont_want_to_fill_in_everything_now_dont_worry_you_can_fill_in_all_the_questions_later_by_editing_each_section) %></div>

<br>

<%= render 'form', what_you_do: @what_you_do %>

app/views/what_you_dos/show.html.erb
<% title @what_you_do.practice.name %>

<div class="link-action">
<% if account_signed_in? %>
  <% if current_account.admin? or current_account.id == @what_you_do.practice.account.id %>
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@what_you_do.practice), :class => "btn btn-warning" %>
      <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@what_you_do.practice), :class => "btn btn-secondary" %>
  <% end %>
<% end %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to truncate(@what_you_do.practice.location.name, length: 12), location_path(@what_you_do.practice.location), title: @what_you_do.practice.location.name,  :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @what_you_do.practice.name.truncate(18) , practice_path(@what_you_do.practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), practice_what_you_do_path(@what_you_do.practice, @what_you_do.practice.what_you_do), :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), practice_characterise_path(@what_you_do.practice, @what_you_do.practice.characterise), :class => "nav-link" if @what_you_do.practice.characterise %>
  </li>  
  <li class="nav-item">
    <%= link_to "#{t(:gallery)} (#{@what_you_do.practice.medias.count})", practice_gallery_path(@what_you_do.practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:documents)} (#{@what_you_do.practice.documents.count})", practice_documents_path(@what_you_do.practice), :class => "nav-link" %>
  </li>
</ul>

<br>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <br>
    <% if @what_you_do.where_it_is_realized.blank? and
      @what_you_do.summary_description_of_agroecological_practice.blank? and
      @what_you_do.type_of_agroecological_practice.blank? and
      @what_you_do.practical_implementation_of_the_practice.blank? and
      @what_you_do.why_you_use_and_what_you_expect_from_this_practice.blank? and
      @what_you_do.land_size.blank? and
      @what_you_do.substitution_of_less_ecological_alternative.blank? %>
      <h3><%= t(:no_data_has_been_registered_so_far) %>
        <% if account_signed_in? %>
          <% if current_account.admin? or current_account.id == @what_you_do.practice.account.id %>
            <%= link_to t(:register), edit_practice_what_you_do_path(@what_you_do.practice, @what_you_do) %>
          <% end %>
        <% end %>
      </h3>
    <% else %>
      <% if ! @what_you_do.where_it_is_realized.blank? %>
        <div class="practices-box">
          <%= "<h4>#{t(:where_it_is_realized)}</h4><div class='text-box'>#{@where_it_is_realized_options.key(@what_you_do.where_it_is_realized)}</div>".html_safe %>
        </div>
      <% end %>

      <% if ! @what_you_do.summary_description_of_agroecological_practice.blank? %>
        <div class="practices-box bg-light"><%= "<h4>#{t(:summary_description_of_agroecological_practice)}</h4><div class='text-box'>#{simple_format (h @what_you_do.summary_description_of_agroecological_practice).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
      <% end %>

      <%  if ! @what_you_do.type_of_agroecological_practice.blank? %>
        <div class="practices-box"><%= "<h4>#{t(:type_of_agroecological_practice)}</h4><div class='text-box'>#{simple_format (h @what_you_do.type_of_agroecological_practice).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
      <% end %>

      <% if ! @what_you_do.practical_implementation_of_the_practice.blank? %>
        <div class="practices-box bg-light"><%= "<h4>#{t(:practical_implementation_of_the_practice)}</h4><div class='text-box'>#{simple_format (h @what_you_do.practical_implementation_of_the_practice).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
      <% end %>

      <% if ! @what_you_do.why_you_use_and_what_you_expect_from_this_practice.blank? %>
        <div class="practices-box"><%= "<h4>#{t(:why_you_use_and_what_you_expect_from_this_practice)}</h4><div class='text-box'>#{simple_format (h @what_you_do.why_you_use_and_what_you_expect_from_this_practice).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
      <% end %>

      <% if ! @what_you_do.land_size.blank? %>
        <div class="practices-box bg-light"><%= "<h4>#{t(:land_size)}</h4><div class='text-box'>#{@what_you_do.land_size} #{@what_you_do.unit_of_measure} </div>".html_safe %></div>
      <% end %>

      <% if ! @what_you_do.substitution_of_less_ecological_alternative.blank? %>
        <div class="practices-box">
          <%= "<h4>#{t(:substitution_of_less_ecological_alternative)}</h4><div class='text-box'>#{@yes_no_i_am_not_sure_not_applicable_options.key(@what_you_do.substitution_of_less_ecological_alternative)}</div>".html_safe %>
          <%= "<br><strong>#{t(:details)}</strong><div class='text-box'>#{simple_format (h @what_you_do.substitution_of_less_ecological_alternative_details).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe unless @what_you_do.substitution_of_less_ecological_alternative_details.blank? %>
        </div>
      <% end %>

      <% if account_signed_in? %>
        <% if current_account.admin? or current_account.id == @what_you_do.practice.account.id %>
          <hr>
          <div id="practice-footer">
            <div class="form-actions">
              <%= link_to t(:edit), edit_practice_what_you_do_path(@what_you_do.practice, @what_you_do), :class => 'btn btn-success' %>
            </div>
          </div>
        <% end %>
      <% end %>
      <br><br>
    <% end %>
  </div>
</div>