config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jobs, only: [:create]

  authenticate :account, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  scope "(:locale)", locale: /en|pt-BR|es|fr/ do
    get "health" => "rails/health#show", as: :rails_health_check
    get "errors/not_found"
    get "errors/internal_server_error"

    root to: "home#index"
    get "home/index"

    get "reduced_map", to: "home#reduced_map"
    get "map", to: "home#index"
    get "landing", to: "about#landing"
    get "about", to: "about#index"
    get "who_we_are", to: "about#who_we_are"
    get "how_to_register", to: "about#how_to_register"
    get "partners", to: "about#partners"
    get "friends", to: "about#partners"
    get "manual", to: "about#manual"
    get "license", to: "about#license"
    get "source_code_license", to: "about#source_code_license"
    get "thank_you_notes", to: "about#thank_you_notes"
    get "contact", to: "about#contact"
    get "projects_and_groups", to: "about#projectsandgroups"
    get "dashboard", to: "dashboard#index"
    get "privacy_policy", to: "about#privacy_policy"

    get "coordinates", to: "locations#coordinates"
    get "countries", to: "locations#countries"
    get "/gallery", to: "medias#gallery"

    put "/practices/:id/like", to: "practices#like", as: "like_practice"
    put "/locations/:id/like", to: "locations#like", as: "like_location"
    post "/accounts/:id/message", to: "accounts#message", as: "message_account"
    post "/home/message", to: "home#message", as: "message_contact"
    post "/locations/:id/sensors", to: "locations#sensors", as: "sensors_location"
    get "/locations/:id/sensors", to: "locations#show_sensors", as: "show_sensors_location"

    resources :practices
    resources :acknowledges
    resources :evaluates
    resources :characterises
    resources :what_you_dos
    resources :comments

    resources :practices do
      resources :acknowledges
      resources :evaluates
      resources :characterises
      resources :what_you_dos
      resources :medias
      resources :documents
      resources :comments
      get "/gallery" => "medias#gallery"
    end

    resources :locations do
      get "/gallery" => "medias#gallery"
      resources :practices
      resources :medias
      resources :documents
    end

    devise_for :accounts, controllers: {
      registrations: "accounts/registrations",
      sessions: "accounts/sessions",
      confirmations: "accounts/confirmations"
    }

    resources :accounts do
      resources :locations
      resources :practices
      resources :medias
      get "/gallery" => "medias#gallery"
    end

    post "login", to: "authentication#login"
    post "signup", to: "authentication#signup"
    post "validate_jwt_token", to: "authentication#validate_jwt_token"

    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
    match "/422", to: "errors#unprocessable_entity", via: :all

    scope(accounts: {}) do
      resources :accounts, path: "usuarios"
      resources :accounts, path: "contributors"
    end

    scope(locations: {}) do
      resources :locations, path: "locais"
    end

    scope(practices: {}) do
      resources :practices, path: "agroecological-experiences"
      resources :practices, path: "experiencia_agroecologicas"
      resources :practices, path: "agroforestry"
      resources :practices, path: "experiences"
      resources :practices, path: "safs"
      resources :practices, path: "news"
    end
  end
end

app/models/acknowledge.rb
# frozen_string_literal: true

class Acknowledge < ApplicationRecord
  belongs_to :practice
  validates :practice, presence: true

  before_save do
    self.knowledge_source.gsub!(/[\[\]"]/, "") if attribute_present?("knowledge_source")
  end
end

app/controllers/acknowledges_controller.rb
# frozen_string_literal: true

class AcknowledgesController < ApplicationController
  skip_before_action :authenticate, except: %i[index, show], if: -> { request.format.json? }
  before_action :authenticate_account!, only: %i[new edit update destroy], if: -> { !request.format.json? }

  before_action :authenticate_account!, only: %i[new edit update destroy]
  before_action -> { check_owner Acknowledge.find(params[:id]).practice.account_id }, only: %i[edit update destroy]

  before_action :set_acknowledge, only: %i[ show edit update destroy ]
  before_action :load_practice, only: %i[ edit ]
  before_action :load_options_acknowledges

  # GET /acknowledges or /acknowledges.json
  def index
    @acknowledges = Acknowledge.all
  end

  # GET /acknowledges/1 or /acknowledges/1.json
  def show
  end

  # GET /acknowledges/new
  def new
    begin
      @practice = Practice.friendly.find(params[:practice_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to locations_path, notice: "This Practice doesn't exist."
    end

    @acknowledge = Acknowledge.new
  end

  # GET /acknowledges/1/edit
  def edit
  end

  # POST /acknowledges or /acknowledges.json
  def create
    @acknowledge = Acknowledge.where(practice_id: params[:acknowledge][:practice_id]).first
    respond_to do |format|
      if @acknowledge
        @acknowledge.update(acknowledge_params)
        format.html { redirect_to location_practice_path(@acknowledge.practice.location, @acknowledge.practice), notice: "Acknowledges was successfully Updated." }
        format.json { render json: { message: "created" }, status: :created }
      else
        @acknowledge = Acknowledge.new(acknowledge_params)
        if @acknowledge.save
          format.html { redirect_to location_practice_path(@acknowledge.practice.location, @acknowledge.practice), notice: "Acknowledges was successfully created." }
          format.json { render :show, status: :created, location: @acknowledge }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @acknowledge.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /acknowledges/1 or /acknowledges/1.json
  def update
    respond_to do |format|
      if @acknowledge.update(acknowledge_params)
        format.html { redirect_to acknowledge_url(@acknowledge), notice: "Acknowledge was successfully updated." }
        format.json { render :show, status: :ok, location: @acknowledge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @acknowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acknowledges/1 or /acknowledges/1.json
  def destroy
    @acknowledge.destroy

    respond_to do |format|
      format.html { redirect_to acknowledges_url, notice: "Acknowledge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acknowledge
      @acknowledge = Acknowledge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def acknowledge_params
      if request.format.json?
        params.require(:acknowledge).permit(:practice_id, :knowledge_timing, :knowledge_products, :knowledge_source_details, :knowledge_timing_details, :uptake_motivation, :knowledge_source)
      else
        params.require(:acknowledge).permit(:practice_id, :knowledge_timing, :knowledge_products, :knowledge_source_details, :knowledge_timing_details, :uptake_motivation, knowledge_source: [])
      end
    end

    def load_practice
      @practice = Practice.friendly.find(params[:practice_id])
    end
end

app/helpers/acknowledges_helper.rb
# frozen_string_literal: true

module AcknowledgesHelper
  def checked_knowledge_source(area)
    @acknowledge.knowledge_source.nil? ? false : @acknowledge.knowledge_source.match(area)
  end
end

app/views/acknowledges/_form.html.erb
<%= form_for(acknowledge, html: { multipart: true }) do |f| %>
  <%= link_to t(:back), "javascript:history.back()", class: "btn btn-danger btn-lg", style: "float: left; margin-bottom: 16px;" unless params["action"] == 'edit' %>
  <% button_name = t(:save) %>
  <%= f.submit button_name, class: "btn btn-warning btn-lg", style: "float: right; margin-bottom: 16px;" %>
  <br>
  <br>
  <% if acknowledge.errors.any? %>
    <div id="error_explanation">
      <b><%= acknowledge.errors.count.to_s + " Error(s)" %></b>
      <br>
      <br>
      <% acknowledge.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %><br>
    </div>
  <% end %>
  <div class="form-group row">
    <div class="col-sm-10">
      <% if params[:practice_id] %>
        <%= f.hidden_field :practice_id, id: "practice_id", :value => Practice.friendly.find(params[:practice_id]).id %>
      <% else %>
        <%= f.hidden_field :practice_id, id: "practice_id", :value => @acknowledge.practice.id %>
      <% end %>
    </div>
  </div>
  <div class="forms">
    <div class="form-group row bg-light">
      <%= f.label t(:knowledge_source), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <% i = 0 %>
        <div style="text-align: left;">
          <% @knowledge_source_options.each do |option| %>
            <%= check_box_tag 'acknowledge[knowledge_source][]', option[1], checked_knowledge_source(option[1]), id: 'knowledge_source' %> <%= i = i + 1%> - <%= option[0] %>
            <br>
          <% end %>
          <br>
          <%= f.text_area :knowledge_source_details, class: "form-control", :rows => "3", :placeholder => t(:please_provide_additional_details) %>
        </div>
        <div class="tip">
          <%= t(:how_did_you_learn_about_the_practice_you_can_choose_more_than_one_option) %>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <%= f.label t(:knowledge_timing), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:knowledge_timing, @knowledge_timing_options, :last, :first, { :include_blank => t(:select_an_option) }, { class: "form-control selectpicker", "data-live-search": true }) %>
        <%= f.text_area :knowledge_timing_details, class: "form-control", :rows => "3", :placeholder => t(:please_provide_additional_details) %>
        <div class="tip">
          <%= t(:how_long_ago_did_you_learn_about_the_practice) %>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group row bg-light">
      <%= f.label t(:uptake_motivation), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.text_area :uptake_motivation, class: "form-control", :rows => "6" %>
        <div class="tip">
          <%= t(:what_motivated_you_to_adopt_the_practice) %>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <%= f.label t(:knowledge_products), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.text_area :knowledge_products, class: "form-control", :rows => "6" %>
        <div class="tip">
          <%= t(:knowledge_products_tip) %>
        </div>
      </div>
    </div>
    <%= f.submit button_name, class: "btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/acknowledges/edit.html.erb
<% title t(:acknowledge) %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to @acknowledge.practice.name.truncate(25), practice_path(@acknowledge.practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)}", "#", :class => "nav-link active" %>
  </li>
</ul>
<br>

<%= render 'form', acknowledge: @acknowledge %>

app/views/acknowledges/new.html.erb
<% title t(:acknowledge) %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to t(:practices), practices_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:evaluate), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:acknowledge), "#", :class => "nav-link active" %>
  </li>
</ul>

<br>

<div class="tip"><%= t(:if_you_dont_want_to_fill_in_everything_now_dont_worry_you_can_fill_in_all_the_questions_later_by_editing_each_section) %></div>

<br>

<%= render 'form', acknowledge: @acknowledge %>

app/views/acknowledges/show.html.erb
<% title @acknowledge.practice.name %>
<div class="link-action">
  <% if account_signed_in? %>
    <% if current_account.admin? or current_account.id == @acknowledge.practice.account.id %>
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@acknowledge.practice), :class => "btn btn-warning" %>
      <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@acknowledge.practice), :class => "btn btn-secondary" %>
    <% end %>
  <% end %>
</div>
<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to truncate(@acknowledge.practice.location.name, length: 12), location_path(@acknowledge.practice.location), title: @acknowledge.practice.location.name,  :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @acknowledge.practice.name.truncate(18) , practice_path(@acknowledge.practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), practice_what_you_do_path(@acknowledge.practice, @acknowledge.practice.what_you_do), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), practice_characterise_path(@acknowledge.practice, @acknowledge.practice.characterise), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:evaluate), practice_evaluate_path(@acknowledge.practice, @acknowledge.practice.evaluate), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:acknowledge), practice_acknowledge_path(@acknowledge.practice, @acknowledge.practice.acknowledge), :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:gallery)} (#{@acknowledge.practice.medias.count})", practice_gallery_path(@acknowledge.practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:documents)} (#{@acknowledge.practice.documents.count})", practice_documents_path(@acknowledge.practice), :class => "nav-link" %>
  </li>
</ul>
<br>
<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <br>
    <% if @acknowledge.knowledge_source.blank? and
      @acknowledge.knowledge_timing.blank? and
      @acknowledge.knowledge_products.blank? and
      @acknowledge.uptake_motivation.blank?
    %>
    <h3><%= t(:no_data_has_been_registered_so_far) %>
      <% if account_signed_in? %>
        <% if current_account.admin? or current_account.id == @acknowledge.practice.account.id %>
          <%= link_to t(:register), edit_practice_acknowledge_path(@acknowledge.practice, @acknowledge) %>
        <% end %>
      <% end %>
    </h3>
  <% else %>
    <% if ! @acknowledge.knowledge_source.blank? %>
      <%
         knowledge_source = @acknowledge.knowledge_source.split(',').map { | item | t(item.strip.gsub(/\s+/, '_').gsub(/-/, '_').downcase.to_sym) }
         knowledge_source = knowledge_source.join(", ")
      %>
      <div class="practices-box bg-light">
        <%= "<h4>#{t(:knowledge_source)}</h4><div class='text-box'>#{knowledge_source.gsub(/,/, '<br/>')}<br></div>".html_safe %>
        <%= "<br><strong>#{t(:details)}</strong><div class='text-box'>#{simple_format (h @acknowledge.knowledge_source_details).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe unless @acknowledge.knowledge_source_details.blank? %>
      </div>
    <% end %>
    <% if ! @acknowledge.knowledge_timing.blank? %>
      <div class="practices-box">
        <%= "<h4>#{t(:knowledge_timing)}</h4><div class='text-box'>#{@knowledge_timing_options.key(@acknowledge.knowledge_timing)}</div>".html_safe %>
        <%= "<br><strong>#{t(:details)}</strong><div class='text-box'>#{simple_format (h @acknowledge.knowledge_timing_details).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe unless @acknowledge.knowledge_timing_details.blank? %>
      </div>
    <% end %>
    <% if ! @acknowledge.uptake_motivation.blank? %>
      <div class="practices-box bg-light"><%= "<h4>#{t(:uptake_motivation)}</h4><div class='text-box'>#{simple_format (h @acknowledge.uptake_motivation).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
    <% end %>
    <% if ! @acknowledge.knowledge_products.blank? %>
      <div class="practices-box"><%= "<h4>#{t(:knowledge_products)}</h4><div class='text-box'>#{simple_format (h @acknowledge.knowledge_products).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
    <% end %>
    <% if account_signed_in? %>
      <% if current_account.admin? or current_account.id == @acknowledge.practice.account.id %>
        <hr>
        <div id="practice-footer">
          <div class="form-actions">
            <%= link_to t(:edit), edit_practice_acknowledge_path(@acknowledge.practice, @acknowledge), :class => 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    <% end %>
    <br>
    <br>
  <% end %>
</div>
</div>