config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jobs, only: [:create]

  authenticate :account, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  scope "(:locale)", locale: /en|pt-BR|es|fr/ do
    get "health" => "rails/health#show", as: :rails_health_check
    get "errors/not_found"
    get "errors/internal_server_error"

    root to: "home#index"
    get "home/index"

    get "reduced_map", to: "home#reduced_map"
    get "map", to: "home#index"
    get "landing", to: "about#landing"
    get "about", to: "about#index"
    get "who_we_are", to: "about#who_we_are"
    get "how_to_register", to: "about#how_to_register"
    get "partners", to: "about#partners"
    get "friends", to: "about#partners"
    get "manual", to: "about#manual"
    get "license", to: "about#license"
    get "source_code_license", to: "about#source_code_license"
    get "thank_you_notes", to: "about#thank_you_notes"
    get "contact", to: "about#contact"
    get "projects_and_groups", to: "about#projectsandgroups"
    get "dashboard", to: "dashboard#index"
    get "privacy_policy", to: "about#privacy_policy"

    get "coordinates", to: "locations#coordinates"
    get "countries", to: "locations#countries"
    get "/gallery", to: "medias#gallery"

    put "/practices/:id/like", to: "practices#like", as: "like_practice"
    put "/locations/:id/like", to: "locations#like", as: "like_location"
    post "/accounts/:id/message", to: "accounts#message", as: "message_account"
    post "/home/message", to: "home#message", as: "message_contact"
    post "/locations/:id/sensors", to: "locations#sensors", as: "sensors_location"
    get "/locations/:id/sensors", to: "locations#show_sensors", as: "show_sensors_location"

    resources :practices
    resources :acknowledges
    resources :evaluates
    resources :characterises
    resources :what_you_dos
    resources :comments

    resources :practices do
      resources :acknowledges
      resources :evaluates
      resources :characterises
      resources :what_you_dos
      resources :medias
      resources :documents
      resources :comments
      get "/gallery" => "medias#gallery"
    end

    resources :locations do
      get "/gallery" => "medias#gallery"
      resources :practices
      resources :medias
      resources :documents
    end

    devise_for :accounts, controllers: {
      registrations: "accounts/registrations",
      sessions: "accounts/sessions",
      confirmations: "accounts/confirmations"
    }

    resources :accounts do
      resources :locations
      resources :practices
      resources :medias
      get "/gallery" => "medias#gallery"
    end

    post "login", to: "authentication#login"
    post "signup", to: "authentication#signup"
    post "validate_jwt_token", to: "authentication#validate_jwt_token"

    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
    match "/422", to: "errors#unprocessable_entity", via: :all

    scope(accounts: {}) do
      resources :accounts, path: "usuarios"
      resources :accounts, path: "contributors"
    end

    scope(locations: {}) do
      resources :locations, path: "locais"
    end

    scope(practices: {}) do
      resources :practices, path: "agroecological-experiences"
      resources :practices, path: "experiencia_agroecologicas"
      resources :practices, path: "agroforestry"
      resources :practices, path: "experiences"
      resources :practices, path: "safs"
      resources :practices, path: "news"
    end
  end
end

app/models/practice.rb
# frozen_string_literal: true

class Practice < ApplicationRecord
  paginates_per 6

  scope :by_name, -> (name) { where("practices.name ILIKE ?", "%#{name}%") }
  scope :by_food_system_components_addressed, -> (food_system_components_addressed) { joins(:characterise).where("characterises.food_system_components_addressed ILIKE ?", "%#{food_system_components_addressed}%") }
  scope :by_agroecology_principles_addressed, -> (agroecology_principles_addressed) { joins(:characterise).where("characterises.agroecology_principles_addressed ILIKE ?", "%#{agroecology_principles_addressed}%") }
  scope :by_where_it_is_realized, -> (where_it_is_realized) { joins(:what_you_do).where("what_you_dos.where_it_is_realized ILIKE ?", "%#{where_it_is_realized}%") }
  scope :by_knowledge_source, -> (knowledge_source) { joins(:acknowledge).where("acknowledges.knowledge_source ILIKE ?", "%#{knowledge_source}%") }
  scope :by_farm_and_farming_system, -> (farm_and_farming_system) { joins(:location).where("locations.farm_and_farming_system ILIKE ?", "%#{farm_and_farming_system}%") }
  scope :by_farm_and_farming_system_complement, -> (farm_and_farming_system_complement) { joins(:location).where("locations.farm_and_farming_system_complement ILIKE ?", "%#{farm_and_farming_system_complement}%") }
  scope :by_country, -> (country) { joins(:location).where("locations.country ILIKE ?", "%#{country}%") }
  scope :by_continent, -> (continent) { joins(:location).where("locations.continent ILIKE ?", "%#{continent}%") }
  scope :by_substitution_of_less_ecological_alternative, -> (substitution_of_less_ecological_alternative) { joins(:what_you_do).where("what_you_dos.substitution_of_less_ecological_alternative ILIKE ?", "%#{substitution_of_less_ecological_alternative}%") }
  scope :by_does_it_help_restore_land, -> (does_it_help_restore_land) { joins(:evaluate).where("evaluates.does_it_help_restore_land ILIKE ?", "%#{does_it_help_restore_land}%") }
  scope :by_does_it_work_in_degraded_environments, -> (does_it_work_in_degraded_environments) { joins(:evaluate).where("evaluates.does_it_work_in_degraded_environments ILIKE ?", "%#{does_it_work_in_degraded_environments}%") }
  scope :by_knowledge_and_skills_required_for_practice, -> (knowledge_and_skills_required_for_practice) { joins(:evaluate).where("evaluates.knowledge_and_skills_required_for_practice ILIKE ?", "%#{knowledge_and_skills_required_for_practice}%") }

  has_one :what_you_do, dependent: :destroy
  has_one :characterise, dependent: :destroy
  has_one :evaluate, dependent: :destroy
  has_one :acknowledge, dependent: :destroy

  has_many :medias, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :photo do |attachable|
    attachable.variant :original, resize_to_limit: [1920, nil]
    attachable.variant :medium, resize_to_limit: [600, nil]
    attachable.variant :thumb, resize_to_limit: [300, nil]
  end

  belongs_to :account
  belongs_to :location

  validates :name, presence: true
  validates_length_of :name, minimum: 2
  validates_length_of :name, maximum: 255
  validate :acceptable_photo

  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save do
    self.name = name.strip
  end

  protected
    def should_generate_new_friendly_id?
      name_changed?
    end

    def acceptable_photo
      return unless photo.attached?

      unless photo.blob.byte_size <= 16.megabyte
        errors.add(:photo, "Size Limit is 16 Mb")
      end

      acceptable_types = ["image/jpeg", "image/png", "image/gif", "image/webp"]
      unless acceptable_types.include?(photo.content_type)
        errors.add(:photo, "must be a JPEG, PNG, GIF or WebP")
      end
    end

    require "csv"
    def self.to_csv
      cols = column_names.map(&:clone)

      cols.delete("slug")
      cols.delete("account_id")
      cols.delete("location_id")
      cols.delete("created_at")
      cols.delete("updated_at")

      cols.push("description")
      cols.push("agroecology_principles_addressed")
      cols.push("food_system_components_addressed")
      cols.push("location_name")
      cols.push("created_at")
      cols.push("updated_at")

      CSV.generate do |csv|
        csv << cols

        cols.delete("description")
        cols.delete("agroecology_principles_addressed")
        cols.delete("food_system_components_addressed")
        cols.delete("location_name")
        cols.delete("created_at")
        cols.delete("updated_at")

        Practice.all.joins(:location, :what_you_do, :characterise).order(:id).each do |practice|
          vals = practice.attributes.values_at(*cols).map(&:clone)
          vals.push(practice.what_you_do.attributes["summary_description_of_agroecological_practice"])
          vals.push(practice.characterise.attributes["agroecology_principles_addressed"])
          vals.push(practice.characterise.attributes["food_system_components_addressed"])
          vals.push(practice.location.attributes["name"])
          vals.push(practice.attributes["created_at"])
          vals.push(practice.attributes["updated_at"])
          csv << vals
        end
      end
    end
end

app/controllers/practices_controller.rb
# frozen_string_literal: true

class PracticesController < ApplicationController
  skip_before_action :authenticate, except: %i[index, show], if: -> { request.format.json? }
  before_action :authenticate_account!, only: %i[new edit update destroy like], if: -> { !request.format.json? }

  before_action lambda { check_owner Practice.friendly.find(params[:id]).account_id }, only: %i[edit update destroy]
  before_action :set_practice, only: %i[show edit update destroy]
  before_action :load_locations, except: %i[index show]
  before_action :load_location
  before_action :load_account
  before_action :load_principles
  before_action :load_system_options
  before_action :load_locations, only: %i[new]
  before_action :load_comments, only: %i[show]
  before_action :load_total

  # GET /practices
  # GET /practices.json
  def index
    @practices = if params[:filter]
      filter
    else
      if request.format == :html
        all
      elsif request.format == :csv
        respond_to do |format|
          format.csv { send_data Practice.to_csv, filename: "practices-#{DateTime.now.strftime("%Y-%m-%d")}.csv" }
        end
      else
        if params[:page]
          Practice.all.includes(:account, :location).order("updated_at DESC").with_attached_photo.page(params[:page])
        else
          Practice.all.includes(:account, :location).order("updated_at DESC").with_attached_photo
        end
      end
    end
  end

  def all
    @practices = if params[:location_id]
      Practice.where(location_id: @location.id).sort_by(&:updated_at).reverse
    elsif params[:account_id]
      Practice.where(account_id: @account.id).sort_by(&:updated_at).reverse
    else
      Practice.includes(:account, :location).with_attached_photo.order("updated_at DESC").page(params[:page])
    end
  end
  def filter
    @practices = Practice.unscoped
    @practices = @practices.by_name(params[:name]) unless params[:name].blank?
    @practices = @practices.by_food_system_components_addressed(params[:components]) unless params[:components].blank?
    @practices = @practices.by_agroecology_principles_addressed(params[:principles]) unless params[:principles].blank?
    @practices = @practices.by_farm_and_farming_system(params[:system_functions]) unless params[:system_functions].blank?
    @practices = @practices.by_farm_and_farming_system_complement(params[:system_components]) unless params[:system_components].blank?
    @practices = @practices.by_country(params[:country]) unless params[:country].blank?
    @practices = @practices.by_continent(params[:continent]) unless params[:continent].blank?
    @practices = @practices.with_attached_photo
    @total = @practices.count
    if request.format == :html
      @practices = @practices.order("practices.updated_at DESC").page(params[:page])
    else
      @practices = @practices.order("practices.updated_at DESC")
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @comment = Comment.new

    if (not browser.bot?) && (not request.is_crawler?)
      @practice.visits += 1
      @practice.save!
    end
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit; end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)

    if request.format.json?
      if params[:base64Image]
        base64Image = params[:base64Image]
        decoded_data = Base64.decode64(base64Image)
        @practice.photo = {
                            io: StringIO.new(decoded_data),
                            content_type: "image/jpeg",
                            filename: "image.jpg"
                          }
      end

      @practice.account_id = authenticate.id
    else
      @practice.account_id = current_account.id unless current_account.admin?
    end

    respond_to do |format|
      if @practice.save

        summary_description = params[:summaryDescription] || ""
        where_it_is_realized = params[:whereItIsRealized] || ""

        @what_you_do = WhatYouDo.new(practice_id: @practice.id,
                                     summary_description_of_agroecological_practice: summary_description,
                                     where_it_is_realized:).save!
        @characterise = Characterise.new(practice_id: @practice.id).save!
        @evaluate = Evaluate.new(practice_id: @practice.id).save!
        @acknowledge = Acknowledge.new(practice_id: @practice.id).save!

        format.html { redirect_to new_practice_what_you_do_path(@practice), notice: "Practice Registered" }
        format.json { render json: { message: "created" }, status: :created }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: "A Practice has been Updated" }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: "Practice has been Removed." }
      format.json { head :no_content }
    end
  end

  def like
    @practice = Practice.friendly.find(params[:id])
    @like = Like.new(account_id: current_account.id, practice_id: @practice.id)

    if @like.save
      subject = "[Agroecology Map] Someone liked your agroecological practice. "
      body = "Liked by: #{@like.account.name} (" + account_url(@like.account) + ")"
      body += "\r\n \r\n"
      body += "Link to your practice: " + location_practice_url(@practice.location, @practice)
      body += "\r\n \r\n"

      if @practice.account.id != current_account.id
        MailJob.perform_async(@practice.account.email, subject, body)
      end

      redirect_to practice_path(@practice), notice: "Your like has been registered! Thanks!!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      if request.format.json?
        params.require(:practice).permit(:name, :photo, :slug, :location_id, :account_id, :base64Image)
      else
        params.require(:practice).permit(:name, :photo, :slug, :location_id, :account_id)
      end
    end

    def load_location
      @location = Location.friendly.find(params[:location_id]) if params[:location_id]
    end

    def load_account
      @account = Account.friendly.find(params[:account_id]) if params[:account_id]
    end

    def load_comments
      @practice_id = Practice.friendly.find(params[:id]).id
      @comments = Comment.where(practice_id: @practice_id).page(params[:page])
    end

    def load_total
      @total = Practice.count
    end
end

app/views/practices/_comment.html.erb
<%= form_for([@practice, comment], html: { multipart: true }) do |f| %>
  <div class="col-xs-4" style="padding-bottom: 25px">
    <%= f.text_area :comment, rows: 4, class: "form-control", placeholder: t(:comment) %>
    <%= f.submit t(:submit_comment), class: "btn btn-info", style: "float: right; margin-top: 8px; margin-bottom: 8px;" %>
  </div>
<% end %>

app/views/practices/index.html.erb
<% title t(:practices) %>

<div class="link-action">
  <%= link_to (bootstrap_icon "clipboard-check") + " " + t(:register_new_practice), new_practice_path, :class => "btn btn-info" %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to @location.name.truncate(25), location_path(@location), title: @location.name, :class => "nav-link" %>
    </li>
  <% end %>

  <li class="nav-item">
    <% if params[:location_id] %>
      <%= link_to t(:practices) + " (#{@practices.count})", "#", :class => "nav-link active" %>
    <% else %>
      <% if @account.blank? %>
        <%= link_to t(:practices) + " (#{@practices.count} #{t(:of)} #{@total})", "#", :class => "nav-link active" %>
      <% else %>
        <%= link_to t(:practices) + " #{ @account.blank? ? '' : ' (' + @account.name.truncate(16) + ')' }", account_path(@account), :class => "nav-link active" %>
      <% end %>
    <% end %>
  </li>


  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to t(:gallery) + " (#{@location.medias.count})", location_gallery_path(@location.id), :class => "nav-link" %>
    </li>
  <% end %>
</ul>

<% hide_search = false %>
<% if params[:location_id] %>
  <% hide_search = true %>
<% end %>

<% if hide_search == false %>
<div style="text-align: left">
  <%= text_field_tag "search", {}, class: "btn dropdown-toggle btn-default search", placeholder: t(:search) %>
  <%= link_to (bootstrap_icon "search"), "#", id: 'searchButton', onclick: 'filter()' %>
  <span style="font-size: 13px;"><a href="#" onclick="showAdvancedFilters()"><%= t(:show_more_filters) %></a></span>
  <div id="more-filter">
    <br>
    <%= select_tag "system_functions", options_from_collection_for_select(@system_functions_options, :last, :first, params[:system_functions] ? params[:system_functions] : ''), class: "selectpicker",  "data-live-search": true, :include_blank => t(:filter_by_farm_functions) %>
    <%= select_tag "system_components", options_from_collection_for_select(@system_components_options, :last, :first, params[:system_components] ? params[:system_components] : ''), class: "selectpicker",  "data-live-search": true, :include_blank => t(:filter_by_farm_components) %>
    <%= select_tag "components", options_from_collection_for_select(@food_system_components_addressed_options, :last, :first, params[:components] ? params[:components] : ''), class: "selectpicker", "data-live-search": true, :include_blank => t(:filter_by_system_component)  %>
    <%= select_tag "principles", options_from_collection_for_select(@agroecology_principles_addressed_options, :last, :first, params[:principles] ? params[:principles] : ''), class: "selectpicker", "data-live-search": true, :include_blank => t(:filter_by_agroecology_principle) %>
    <%= country_select("country", "country", { selected: params[:country] ? params[:country] : '', :include_blank => t(:country) }, { class: "selectpicker", "data-live-search": true}) %>
    <%= select_tag "continent", options_from_collection_for_select(@continent_options, :last, :first, params[:continent] ? params[:continent] : ''), class: "selectpicker",  "data-live-search": true, :include_blank => t(:filter_by_continent) %>
    <div style="padding-top: 8px; padding-bottom: 8px; align-content: center; text-align: left; font-size: 21px">
      <%= link_to (bootstrap_icon "search", width: 16, style: "margin-bottom: 3px") + " " + t(:filter), "#", onclick: 'filter()', class: "btn btn-warning btn-lg" %>
      <%= link_to " " + t(:clear_filters), practices_path, class: "btn btn-info btn-lg" %>
    </div>
  </div>
</div>
<% else %>
<br><br>
<% end %>

<% if @practices.empty? %>
  <h2>
    <%= t(:no_data_has_been_registered_so_far) %>
    <% if params[:location_id] %>
      <% if account_signed_in? %>
        <% if current_account.admin? or current_account.id == @location.account.id %>
          <%= link_to t(:add_a_practice), new_location_practice_path(@location) unless @location.blank? %>
        <% end %>
      <% end %>
    <% end %>
  </h2>
<% else %>
<%=  %>
  <% if @account.blank? and params[:location_id].blank? %>
      <span style="font-size: 13px; float: right;">
        <a href="/practices.json">Export as JSON</a>
        |
        <a href="/practices.csv">CSV</a>
      </span><br>
  <% end %>
  <div class="row">
    <% @practices.each do |practice| %>
      <div class="col-sm-4" style="cursor: pointer;" onclick="window.location='<%= location_practice_path(practice.location, practice) %>';">
        <div class="card">

          <div class="like">
            <% likes = practice.likes.count.to_s %>
            <% visits = practice.visits.to_s %>
            <%= link_to like_practice_path(practice), method: "put", class: "btn text-white",  style: "background-color: #fff; padding-right: 5px;", disabled: true do %>
              <img src="/like.png" alt="<%= @likes_info %>" title="<%= likes %> Like(s)">
              <span class="badge bg-danger ms-2" style="font-size: 12px;" title="<%= likes %> Like(s)"><%= practice.likes.count.to_s %></span>
            <% end %>
            <div class="btn text-white" style="padding-left: 0px;">
              <img src="<%= image_url("eye.png") %>" alt="Visits" title="<%= visits %> Visit(s)">
              <span class="badge bg-success ms-2 text-white" style="font-size: 12px;" title="<%= visits %> Visit(s)"><%= practice.visits.to_s %></span>
            </div>
          </div>

          <div class="card-img-top thumbnail"><%= link_to photo_thumb(practice, practice.name, true), practice_path(practice), alt: practice.location.name, title: practice.location.name %></div>
           <div class="card-body" style="min-height: 100px;">
              <h4 class="card-title" style="font-size: 18px !important; word-break: break-all;"><%= link_to practice.name.truncate(34), practice_path(practice) %></h4>
              <p class="card-text" style="text-align: center; font-size: 12px;">
                  <%= link_to t(:details), practice_url(practice) %> |
                  <%= link_to t(:location), location_path(practice.location) %> <%= "|" if practice.medias.size > 0 %>
                  <%= link_to t(:gallery) + " (#{practice.medias.size})", practice_gallery_path(practice) if practice.medias.size > 0 %>
              </p>
            </div>
        </div>
        <br>
      </div>
    <% end %>
  </div>

  <% if not params[:account_id] and not params[:location_id] %>
    <div style="margin-top: -14px;">
      <%= paginate @practices %>
    </div>
  <% end %>
<% end %>

<script>
    const controller = 'practices';

    $(document).ready(function () {
        <% if params[:filter].blank? or params[:name] %>
        $("#more-filter").hide();
        $("#searchButton").show();
        <% else %>
        $("#searchButton").hide();
        <% end %>
    });

    $("#search").on('keyup', function (event) {
        if (event.keyCode === 13) {
            filter("search");
        }
    });

    function filter() {
        var name = $("#search").val();
        var system_functions = $("#system_functions :selected").val();
        var system_components = $("#system_components :selected").val();
        var components = $("#components :selected").val();
        var principles = $("#principles :selected").val();
        var country = $("#country_country :selected").val();
        var continent = $("#continent :selected").val();

        var filter = "?filter=true"
        filter += name ? "&name=" + name : "";
        filter += system_functions ? "&system_functions=" + system_functions : "";
        filter += system_components ? "&system_components=" + system_components : "";
        filter += components ? "&components=" + components : "";
        filter += principles ? "&principles=" + principles : "";
        filter += country ? "&country=" + country : "";
        filter += continent ? "&continent=" + continent : "";
        var url = "/" + controller + "/" + filter;

        var lang = '<%= params[:locale] ? params[:locale] : 'en' %>'

        if (url != '/' + controller + '/?filter=true') {
            window.location.href =  '/' + lang + url;
        }
        else {
            window.location.href = '/' + lang + '/' + controller;
        }
    }

    function showAdvancedFilters() {
        $("#more-filter").is(":visible") ? $("#more-filter").hide() : $("#more-filter").show();
        $("#more-filter").is(":visible") ? $("#searchButton").hide() : $("#searchButton").show();
    }
</script>

app/views/practices/show.html.erb
<% title @practice.location.name %>

<div class="link-action">
<% if account_signed_in? %>
  <% if current_account.admin? or current_account.id == @practice.account.id %>
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@practice), :class => "btn btn-warning" %>
      <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@practice), :class => "btn btn-secondary" %>
  <% end %>
<% end %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to truncate(@practice.location.name, length: 12), location_path(@practice.location), title: @practice.location.name,  :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @practice.name.truncate(18) , practice_path(@practice), :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), practice_what_you_do_path(@practice, @practice.what_you_do), :class => "nav-link" if @practice.what_you_do %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), practice_characterise_path(@practice, @practice.characterise), :class => "nav-link" if @practice.characterise %>
  </li>  
  <li class="nav-item">
    <%= link_to "#{t(:gallery)} (#{@practice.medias.count})", practice_gallery_path(@practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:documents)} (#{@practice.documents.count})", practice_documents_path(@practice), :class => "nav-link" %>
  </li>
</ul>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">

    <div class="like">
      <% likes = @practice.likes.count.to_s %>
      <% visits = @practice.visits.to_s %>
      <%= link_to like_practice_path(@practice), method: "put", class: "btn text-white",  style: "background-color: #fff; padding-right: 5px;", disabled: true do %>
        <img src="/like.png" alt="<%= @likes_info %>" title="<%= likes %> Like(s)">
        <span class="badge bg-danger ms-2" style="font-size: 12px;" title="<%= likes %> Like(s)"><%= @practice.likes.count.to_s %></span>
      <% end %>
      <div class="btn text-white" style="padding-left: 0px;">
        <img src="<%= image_url("eye.png") %>" alt="Visits" title="<%= visits %> Visit(s)">
        <span class="badge bg-success ms-2 text-white" style="font-size: 12px;" title="<%= visits %> Visit(s)"><%= @practice.visits.to_s %></span>
      </div>
    </div>

    <div class="thumbnail">
      <%= photo_thumb(@practice, @practice.name, true) %>
    </div>

    <br>
    <h1><%= @practice.name.truncate(128) %></h1>
    <br>

    <% if ! @practice.what_you_do.summary_description_of_agroecological_practice.blank? %>
      <%= "<h4>#{t(:summary_description)}</h4>".html_safe  %>
      <div class="text-box"><%= "<div class='text-box'>#{simple_format (h @practice.what_you_do.summary_description_of_agroecological_practice).gsub(URI.regexp, '<a href="\0">\0</a>')}</div>".html_safe %></div>
    <% end %>

    <%= "<h4>#{t(:location)}</h4>#{link_to @practice.location.name.truncate(64), location_path(@practice.location)}&nbsp;".html_safe if @practice.location.name? %>
    <br><br>
    <%= "<h4>#{t(:registered_on)}</h4><div class='text-box'>#{@practice.created_at.strftime('%Y-%m-%d')}</div>".html_safe %>
    <div class="practices-box bg-light"><%= "<h4>#{t(:responsible_for_information)}</h4>#{link_to @practice.account.name, account_path(@practice.account)}&nbsp;".html_safe if @practice.account.name? %></div>

    <h4><%= @practice.comments.count.to_s + " " + t(:comments) + "(s)" %>:</h4>
    <% if  account_signed_in? %>
      <div class='comment-box'>
        <%= render 'comment', comment: @comment %>
      </div>
    <% end %>

    <%= "<b>#{link_to t(:sign_in_to_comment), new_account_session_path, :class => 'text-danger'}</b>".html_safe if !account_signed_in? %>
    
    <% if @practice.comments.count > 0 %>
      <%= render 'comments', comments: @comments.order(:updated_at).reverse_order %>
    <% end %>

    <% if account_signed_in? %>
      <% if current_account.admin? or current_account.id == @practice.account.id %>
        <br><hr>
        <div id="practice-footer">
          <div class="form-actions">
            <%= link_to t(:edit), edit_location_practice_path(@practice.location, @practice.id), :class => 'btn btn-success' %>
            <%= link_to t(:destroy), practice_path(@practice), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    <% end %>

    <br><br>
  </div>
</div>